### ISSUE TITLE
allow no filtering in speaker.yml XO sets

### ISSUE THREAD

**Issue by Rsantct** [rripio/pre.di.c#15]
As it is already available `none` for DRC sets inside **`speaker.yml`**, it is useful to allow no filtering for some use cases, for example for a full range pasive loudspeaker.

```
DRC:
  filters: [f.drc.L, f.drc.R]
  sets:
    nearfield: [L_DynA42, R_DynA42]
    none: [none, none]
XO:
  filters: [f.fr.L, f.fr.R]
  sets:
    normal: [DynA42_left, DynA42_right]
    none: [none, none]
```

This is the code proposal to allow this under the function **`server_process.change_xovers`** :

```
            if XO_set in gc.speaker['XO']['sets']:
                coeffs = gc.speaker['XO']['sets'][XO_set]
                filters = gc.speaker['XO']['filters']
                # allows no filtering e.g for fullrange loudspeakers
                coeffsTmp = coeffs.copy() # a copy does not modify the original
                for index, item in enumerate(coeffsTmp):
                    if item == 'none':
                        coeffsTmp[index] = '-1'
                    else:
                        coeffsTmp[index] = '"' + item + '"'
                for i in range(len(filters)):
                    bf_cli( 'cfc "' + filters[i] + '" ' + coeffsTmp[i] )

```
